/* ============================================================
   main.js — reads CONFIG and builds the entire page.
   Do not edit this file per-client; edit config.js instead.
   ============================================================ */

document.addEventListener('DOMContentLoaded', () => {
  applyTheme();
  buildMeta();
  buildNavbar();
  buildHero();
  buildTrustBar();
  buildServices();
  buildAbout();
  buildGallery();
  buildProcess();
  buildTestimonials();
  buildContact();
  buildFooter();
  initInteractions();
});

// ── THEME ──────────────────────────────────────────────────
function applyTheme() {
  const r = document.documentElement;
  const p = CONFIG.colorPrimary;
  const a = CONFIG.colorAccent;

  // Darken primary for navy2, lighten accent for gold2
  r.style.setProperty('--navy',  p);
  r.style.setProperty('--navy2', lighten(p, 12));
  r.style.setProperty('--gold',  a);
  r.style.setProperty('--gold2', lighten(a, 18));
}

function lighten(hex, amt) {
  const num = parseInt(hex.replace('#', ''), 16);
  const r = Math.min(255, (num >> 16) + amt);
  const g = Math.min(255, ((num >> 8) & 0xff) + amt);
  const b = Math.min(255, (num & 0xff) + amt);
  return '#' + [r, g, b].map(v => v.toString(16).padStart(2, '0')).join('');
}

// ── META ───────────────────────────────────────────────────
function buildMeta() {
  document.title = CONFIG.metaTitle;
  document.getElementById('meta-desc').setAttribute('content', CONFIG.metaDescription);
  document.getElementById('page-title').textContent = CONFIG.metaTitle;
}

// ── NAVBAR ─────────────────────────────────────────────────
function buildNavbar() {
  document.getElementById('nav-logo').innerHTML = logoHTML();

  const phoneEl = document.getElementById('nav-phone');
  phoneEl.href = `tel:${CONFIG.phone}`;
}

// ── HERO ───────────────────────────────────────────────────
function buildHero() {
  document.getElementById('hero-badge').textContent = CONFIG.heroBadge;

  const title = CONFIG.heroTitle.replace(
    CONFIG.heroHighlight,
    `<span class="highlight">${CONFIG.heroHighlight}</span>`
  );
  document.getElementById('hero-title').innerHTML = title;
  document.getElementById('hero-sub').textContent = CONFIG.heroSub;

  const phoneEl = document.getElementById('hero-phone');
  phoneEl.href = `tel:${CONFIG.phone}`;
  document.getElementById('hero-phone-num').textContent = CONFIG.phone;

  document.getElementById('hero-stats').innerHTML = `
    <div class="stat">
      <span class="stat-num">${CONFIG.statYears}</span>
      <span class="stat-label">${CONFIG.statYearsLabel}</span>
    </div>
    <div class="stat-divider"></div>
    <div class="stat">
      <span class="stat-num">${CONFIG.statProjects}</span>
      <span class="stat-label">${CONFIG.statProjectsLabel}</span>
    </div>
    <div class="stat-divider"></div>
    <div class="stat">
      <span class="stat-num">${CONFIG.statSatisfaction}</span>
      <span class="stat-label">${CONFIG.statSatisfactionLabel}</span>
    </div>
  `;
}

// ── TRUST BAR ──────────────────────────────────────────────
function buildTrustBar() {
  document.getElementById('trust-bar').innerHTML = CONFIG.trustItems
    .map(item => `
      <div class="trust-item">
        <i class="fa-solid ${item.icon}"></i> ${item.text}
      </div>
    `).join('');
}

// ── SERVICES ───────────────────────────────────────────────
function buildServices() {
  document.getElementById('services-grid').innerHTML = CONFIG.services
    .map((s, i) => `
      <div class="service-card" data-delay="${i * 100}">
        <div class="service-icon"><i class="fa-solid ${s.icon}"></i></div>
        <h3>${s.title}</h3>
        <p>${s.desc}</p>
      </div>
    `).join('');

  // Also populate the form's service dropdown
  const select = document.getElementById('service');
  CONFIG.services.forEach(s => {
    const opt = document.createElement('option');
    opt.textContent = s.title;
    select.appendChild(opt);
  });
  const other = document.createElement('option');
  other.textContent = 'Other / Not Sure';
  select.appendChild(other);
}

// ── ABOUT ──────────────────────────────────────────────────
function buildAbout() {
  document.getElementById('about-badge-num').textContent   = CONFIG.aboutBadgeNumber;
  document.getElementById('about-badge-label').textContent = CONFIG.aboutBadgeLabel;
  document.getElementById('about-title').textContent       = `About ${CONFIG.businessName}`;

  document.getElementById('about-paragraphs').innerHTML = CONFIG.aboutParagraphs
    .map(p => `<p>${p}</p>`).join('');

  document.getElementById('about-checklist').innerHTML = CONFIG.aboutChecklist
    .map(item => `
      <li><i class="fa-solid fa-check-circle"></i> ${item}</li>
    `).join('');

  const phoneEl = document.getElementById('about-phone');
  phoneEl.href = `tel:${CONFIG.phone}`;
}

// ── GALLERY ────────────────────────────────────────────────
function buildGallery() {
  document.getElementById('gallery-grid').innerHTML = CONFIG.galleryItems
    .map(item => `
      <div class="gallery-card ${item.size}">
        <div class="gallery-placeholder">
          <i class="fa-solid ${item.icon}"></i>
          <span>${item.label}</span>
        </div>
      </div>
    `).join('');
}

// ── PROCESS ────────────────────────────────────────────────
function buildProcess() {
  document.getElementById('process-steps').innerHTML = CONFIG.processSteps
    .map((step, i) => {
      const arrow = i < CONFIG.processSteps.length - 1
        ? `<div class="step-arrow"><i class="fa-solid fa-arrow-right"></i></div>`
        : '';
      return `
        <div class="step">
          <div class="step-num">0${i + 1}</div>
          <div class="step-icon"><i class="fa-solid ${step.icon}"></i></div>
          <h3>${step.title}</h3>
          <p>${step.desc}</p>
        </div>
        ${arrow}
      `;
    }).join('');
}

// ── TESTIMONIALS ───────────────────────────────────────────
function buildTestimonials() {
  const stars = '<i class="fa-solid fa-star"></i>'.repeat(5);
  document.getElementById('testimonials-grid').innerHTML = CONFIG.testimonials
    .map(t => `
      <div class="testimonial-card">
        <div class="quote-icon"><i class="fa-solid fa-quote-left"></i></div>
        <p>"${t.text}"</p>
        <div class="testimonial-author">
          <div class="author-avatar">${t.initials}</div>
          <div>
            <strong>${t.name}</strong>
            <span>${t.location}</span>
            <div class="review-stars">${stars}</div>
          </div>
        </div>
      </div>
    `).join('');
}

// ── CONTACT ────────────────────────────────────────────────
function buildContact() {
  const rows = [
    { icon: 'fa-phone',        label: 'Phone',    value: CONFIG.phone,    href: `tel:${CONFIG.phone}` },
    { icon: 'fa-location-dot', label: 'Based In', value: `${CONFIG.location}, ${CONFIG.county}` },
    { icon: 'fa-map',          label: 'Coverage', value: CONFIG.coverage },
    { icon: 'fa-clock',        label: 'Hours',    value: CONFIG.hours },
  ];

  if (CONFIG.email) {
    rows.splice(1, 0, { icon: 'fa-envelope', label: 'Email', value: CONFIG.email, href: `mailto:${CONFIG.email}` });
  }

  document.getElementById('contact-details').innerHTML = rows.map(row => {
    const inner = `
      <div class="contact-icon"><i class="fa-solid ${row.icon}"></i></div>
      <div>
        <span class="contact-label">${row.label}</span>
        <span class="contact-value">${row.value}</span>
      </div>
    `;
    return row.href
      ? `<a href="${row.href}" class="contact-item">${inner}</a>`
      : `<div class="contact-item">${inner}</div>`;
  }).join('');
}

// ── FOOTER ─────────────────────────────────────────────────
function buildFooter() {
  document.getElementById('footer-logo').innerHTML = logoHTML();

  document.getElementById('footer-desc').textContent =
    `Professional ${CONFIG.tagline.toLowerCase()} based in ${CONFIG.location}, serving ${CONFIG.coverage}.`;

  document.getElementById('footer-contact-details').innerHTML = `
    <a href="tel:${CONFIG.phone}"><i class="fa-solid fa-phone"></i> ${CONFIG.phone}</a>
    <p><i class="fa-solid fa-location-dot"></i> ${CONFIG.location}, ${CONFIG.county}</p>
    <p><i class="fa-solid fa-clock"></i> ${CONFIG.hours}</p>
  `;

  document.getElementById('footer-bottom-text').innerHTML =
    `&copy; ${new Date().getFullYear()} ${CONFIG.businessName}. All rights reserved. | ${CONFIG.location}, ${CONFIG.county}`;

  const floatCall = document.getElementById('float-call');
  floatCall.href = `tel:${CONFIG.phone}`;
}

// ── SHARED LOGO HTML ───────────────────────────────────────
function logoHTML() {
  const [first, ...rest] = CONFIG.businessName.split('&');
  if (rest.length) {
    return `
      <span class="logo-sb">${first.trim()}<span class="amp">&amp;</span>${rest.join('&').trim()}</span>
      <span class="logo-text">${CONFIG.tagline}</span>
    `;
  }
  return `
    <span class="logo-sb">${CONFIG.businessName}</span>
    <span class="logo-text">${CONFIG.tagline}</span>
  `;
}

// ── INTERACTIONS ───────────────────────────────────────────
function initInteractions() {
  // Navbar scroll effect
  const navbar = document.getElementById('navbar');
  window.addEventListener('scroll', () => {
    navbar.classList.toggle('scrolled', window.scrollY > 60);
  });

  // Mobile burger menu
  const burger = document.getElementById('burger');
  const navLinks = document.getElementById('nav-links');
  burger.addEventListener('click', () => navLinks.classList.toggle('open'));
  navLinks.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', () => navLinks.classList.remove('open'));
  });

  // Scroll-reveal for service cards
  const revealObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (!entry.isIntersecting) return;
      const el = entry.target;
      setTimeout(() => el.classList.add('visible'), parseInt(el.dataset.delay || '0', 10));
      revealObserver.unobserve(el);
    });
  }, { threshold: 0.15 });

  document.querySelectorAll('.service-card').forEach(card => revealObserver.observe(card));

  // Active nav link highlight on scroll
  const sections = document.querySelectorAll('section[id]');
  const navItems = document.querySelectorAll('.nav-link');
  const sectionObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (!entry.isIntersecting) return;
      navItems.forEach(link => {
        link.style.color = '';
        if (link.getAttribute('href') === '#' + entry.target.id) {
          link.style.color = 'var(--gold2)';
        }
      });
    });
  }, { threshold: 0.45 });
  sections.forEach(s => sectionObserver.observe(s));

  // Contact form submission (demo — swap setTimeout for a real fetch/Formspree)
  const form = document.getElementById('contact-form');
  const successMsg = document.getElementById('form-success');
  form.addEventListener('submit', (e) => {
    e.preventDefault();
    const btn = form.querySelector('button[type="submit"]');
    btn.disabled = true;
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Sending…';
    setTimeout(() => {
      form.querySelectorAll('input, select, textarea').forEach(el => el.value = '');
      btn.innerHTML = '<i class="fa-solid fa-paper-plane"></i> Send Message';
      btn.disabled = false;
      successMsg.style.display = 'flex';
      setTimeout(() => { successMsg.style.display = 'none'; }, 5000);
    }, 1200);
  });

  // Smooth scroll fallback
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', (e) => {
      const target = document.querySelector(anchor.getAttribute('href'));
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });
}
